# Generated by Django 3.1.2 on 2020-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrelsighting',
            name='date',
            field=models.DateField(help_text='Date of sighting; Format YYYY-MM-DD'),
        ),
    ]
