# Generated by Django 3.1.2 on 2020-10-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20201019_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrelsighting',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', '?')], help_text='Age description', max_length=8),
        ),
    ]
